# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e9b752d3337dc1550d1f21db0bf37e472f7f44e383200896d57c3b8cf3a03f3a502f8cee862cbcdaa78456a574a742e15e7ff3b8e2ca5fee3b6b5e17f5a3821

test:
  secret_key_base: b2a64a93a1e918f393ddb85702b936a0bc66caebfb76fab14d9318b251074476dcd371159640f81a0337b0f0edf48a24d394fbd2609e6c3782ba4a1bc99afd61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
